import smtplib
from email.mime.text import MIMEText 
from email.mime.multipart import MIMEMultipart 

def get_pwd():
    pwd = ""
    with open("lib//data//pwd.txt") as pwd_file:
        pwd = pwd_file.readline() # get password
        pwd_file.close() #close file

    return pwd

def get_email_html(mode, inquiry_info):
    html = ""
    if mode == "user" :
        html = """
                <html>
                <body>
                
                <h2>Your support request \"""" + inquiry_info["title"] + """\" has been received</h2>
                <div class = "user_inquiry">
                    <h3>Title: """+ inquiry_info["title"] +"""</h3>
                    <h3>Detail:</h3>
                    <p>
                        """ + inquiry_info["detail"] +"""
                    </p>
                </div>
                <p>Hello, """ + inquiry_info["last_name"] + " " + inquiry_info["family_name"] + """ <br>
                    This email is automatically generated by <i>StaFiIndia</i>. <br>
                    <b>StaFiIndia Support Team will confirm your inquiry and respond to you within 48 hours</b>.<br><br>
                    Thank you for your support and patience! <br>
                    StaFiIndia Support Team<br><br>
                </p>
                <div class = "contact">
                    <div>
                        <h5>Contact:</h5>
                        <p>
                            Phone number: +0123 4567 8910<br>
                            Email: support_team@StaFiIndia.com<br>
                            Addreess: 457-89, 254 Street, District 7<br>
                        </p>
                    </div>
                    <div>
                        <h5>Working hours</h5>
                        <p>
                            Monday: 9 AM - 5 PM <br>
                            Tuesday: 9 AM - 5 PM <br>
                            Wednesday: 9 AM - 5 PM <br>
                            Thursday: 9 AM - 5 PM <br>
                            Friday: 9 AM - 5 PM <br>
                            Saturday: 10 AM - 5 PM <br>
                            Sunday: 10 AM - 3 PM <br>
                        </p>
                    </div>
                </div>
                </body>
            </html>
        """
    else:
        html = """
            <html>
            <body>
            <h2>User request \"""" + inquiry_info["title"] + """\" has been received</h2>
            <div class = "user_inquiry">
                <h3>Inquiry Info:</h3>
                <h4>Title: """ + inquiry_info["title"] + """</h4>
                <h4>Detail:</h4>
                <p>
                    """ + inquiry_info["detail"] + """
                </p>       
            </div>
            <div class = "user_info">
                <h3>User info:</h3>
                <h4>Name: """ +  inquiry_info["last_name"] + " " + inquiry_info["family_name"]  + """</h4>
                <h4>Email address: """ + inquiry_info["user_email"] + """</h4>   
            </div>
            <div class = "contact">
                <div>
                    <h5>Contact:</h5>
                    <p>
                        Phone number: +0123 4567 8910<br>
                        Email: support_team@StaFiIndia.com<br>
                        Addreess: 457-89, 254 Street, District 7<br>
                    </p>
                </div>
                <div>
                    <h5>Working hours</h5>
                    <p>
                        Monday: 9 AM - 5 PM <br>
                        Tuesday: 9 AM - 5 PM <br>
                        Wednesday: 9 AM - 5 PM <br>
                        Thursday: 9 AM - 5 PM <br>
                        Friday: 9 AM - 5 PM <br>
                        Saturday: 10 AM - 5 PM <br>
                        Sunday: 10 AM - 3 PM <br>
                    </p>
                </div>
            </div>
            </body>
        </html>
        """
    return html

def build_email(mode, to_email, inquiry_info):
    msg = MIMEMultipart() 
    msg['To'] = to_email # to user email 
    msg['Subject'] = "[Request received] " + inquiry_info["title"]
    html = get_email_html(mode, inquiry_info)
    html_msg = MIMEText(html, 'html')
    msg.attach(html_msg)
    return msg

def send_email(f_name, l_name, user_email, inquiry_title, detail):
    ###################################################
    #Title: Python - Sending Email using SMTP
    #Author: tutorialspoint
    #Date: (Unknown)
    #Code version: (Unknown)
    #Availability: https://www.tutorialspoint.com/python/python_sending_email.htm (Accessed 6 May 2022)
    ###################################################

    GG_PORT_NUM = 587 #google smpt server port number
    #admin email info
    admin_account = "temp.acc.lgi@gmail.com"
    password = get_pwd()

    #info 
    inquiry_info = {"family_name": f_name,
                    "last_name": l_name,
                    "user_email": user_email,
                    "title": inquiry_title,
                    "detail": detail
    }

    #connect to google smpt 
    sv = smtplib.SMTP('smtp.gmail.com', GG_PORT_NUM)
    sv.starttls() #use TLS method 
    sv.login(admin_account, password) #login using admin account

    #build and send email to user
    msg = build_email("user", user_email, inquiry_info)
    sv.sendmail(admin_account, user_email, msg.as_string())

    #build and send email to admin
    msg = build_email("admin", admin_account, inquiry_info)
    sv.sendmail(admin_account, admin_account, msg.as_string())
    
    sv.quit() #disconnect server